name: Docker build

on:
  push:
    branches:
      - main
      - docker
  pull_request:

jobs:
  builder:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # We use buildx and its GitHub Actions caching support `type=gha`. For
      # more information, see
      # https://github.com/docker/build-push-action/issues/539
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build base Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
